# General parameters
[config]
reload_apps = true
run_after = [["touch", "~/.config/alacritty/alacritty.toml"],]

# i3
[templates.i3]
input_path = '~/.config/matugen/templates/i3.conf'
output_path = '~/.config/i3/colors.conf'
post_hook = 'i3 reload > /dev/null'

# Polybar
[templates.polybar]
input_path = '~/.config/matugen/templates/polybar.ini'
output_path = '~/.config/polybar/colors.ini'
post_hook = 'polybar-msg cmd restart > /dev/null'

# Alacritty
[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

# Starship
[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

# Rofi
[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'

# Pywalfox
[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

# Gtk 3
[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

# Gtk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'
