palette = 'matugen'

format = """
[╭  ](fg:primary)\
$directory\
$git_branch\
$git_status\
$kubernetes \
$time \
\n$character"""

[character]
format = """
[╰─$symbol](fg:primary) """
success_symbol = '[](fg:bold primary)'
error_symbol = '[](fg:bold error)'

[directory]
format = '[$path](fg:secondary)'
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
disabled = false
symbol = ""
format = '( | [$symbol](fg:tertiary) $branch)'

[git_status]
disabled = false
format = '( [$all_status](fg:on_surface_variant))'

[kubernetes]
disabled = false
style = "fg:on_surface"
format = '( | [$context]($style)( in [$namespace]($style)))'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '| $time'

[palettes.matugen]
primary = "#acc7ff"
secondary = "#bec6dc"
tertiary = "#ddbce0"
surface = "#111318"
surface_variant = "#44474e"
background = "#111318"
error = "#ffb4ab"
on_primary = "#0e2f60"
on_secondary = "#283041"
on_tertiary = "#3f2844"
on_surface = "#e2e2e9"
on_surface_variant = "#c4c6d0"
on_background = "#e2e2e9"
on_error = "#690005"
outline = "#8e9099"
