palette = 'matugen'

format = """
[╭  ](fg:primary)\
$directory\
$git_branch\
$git_status\
$kubernetes \
$time \
\n$character"""

[character]
format = """
[╰─$symbol](fg:primary) """
success_symbol = '[](fg:bold primary)'
error_symbol = '[](fg:bold error)'

[directory]
format = '[$path](fg:secondary)'
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
disabled = false
symbol = ""
format = '( | [$symbol](fg:tertiary) $branch)'

[git_status]
disabled = false
format = '( [$all_status](fg:on_surface_variant))'

[kubernetes]
disabled = false
style = "fg:on_surface"
format = '( | [$context]($style)( in [$namespace]($style)))'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '| $time'

[palettes.matugen]
primary = "#c0c1ff"
secondary = "#c6c4dd"
tertiary = "#e9b9d3"
surface = "#131318"
surface_variant = "#47464f"
background = "#131318"
error = "#ffb4ab"
on_primary = "#292a60"
on_secondary = "#2e2f42"
on_tertiary = "#46263a"
on_surface = "#e4e1e9"
on_surface_variant = "#c8c5d0"
on_background = "#e4e1e9"
on_error = "#690005"
outline = "#918f9a"
