[general]
import = ["~/.config/alacritty/colors.toml"]

[window]
opacity = 0.9
padding = { x = 3, y = 3 }

[cursor.style]
shape = "Beam"
blinking = "Always"

[cursor]
blink_interval = 500

[font]
size = 11
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

